# Generated by Django 2.2.5 on 2019-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.CharField(max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='members',
            name='e_mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
