# Generated by Django 2.2.5 on 2019-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190920_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='last_name',
            field=models.CharField(default='itexas', max_length=50, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.CharField(max_length=30, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='members',
            name='leader',
            field=models.CharField(max_length=50, verbose_name='Lider'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='members',
            name='post',
            field=models.CharField(max_length=30, verbose_name='Cargo'),
        ),
    ]
